services:
    dat-webapp:
        container_name: dat-webapp
        image: dat-webapp:latest
        #runtime: nvidia
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - datapath=/work/models
        networks:
            - dat-network
        volumes:
            - dat-yaml-volume:/work/yaml_dir
            - dat-corpora-volume:/work/uploaded_corpora
        ports:
            - "5000:8000"
    dat-front:
        container_name: dat-front
        image: dat-front:latest
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - "8000:3000"
        networks:
            - dat-network
        volumes:
            - dat-yaml-volume:/yaml_dir

volumes:
    dat-corpora-volume:    
        driver: local
        driver_opts:
            device: ./uploaded_corpora
            o: bind
            type: local
    dat-yaml-volume:
        driver: local
        driver_opts:
            device: ./yaml_dir
            o: bind
            type: local
networks:
    dat-network: