services:
    dat-webapp:
        container_name: dat-webapp
        image: dat-webapp:latest
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - datapath=/work/models
        networks:
            - dat-network
        volumes:
            - ./yaml_dir:/work/yaml_dir
            - ./uploaded_corpora:/work/uploaded_corpora
        ports:
            - "8000:8000"
#volumes:
networks:
    dat-network:                

